### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by georgkrause** [klingtnet/bitwig-akai-apc-mini#1]
Hello,

how is the state of this project? Is it working?

**Comment by klingtnet** [comment]
Hey,

I haven't really worked on it, i.e. it only is a scaffold for a controller extension without functionality. In the meantime I'm using git-moss' [DrivenByMoss](https://github.com/git-moss/DrivenByMoss) bitwig controller extension to drive my APC mini.
If you need an example for programming controller extensions see those two [bitwig-edirol-pcr](https://github.com/klingtnet/bitwig-edirol-pcr) or [bitwig-akai-midimix](https://github.com/klingtnet/bitwig-akai-midimix).
